#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Regenerate the UnicodeData.txt excerpt that alphabets.test.ts checks every
# emitted glyph against. Only the two blocks ProseEdge draws from are kept:
# Letterlike Symbols (U+2100–U+214F) and Mathematical Alphanumeric Symbols
# (U+1D400–U+1D7FF).
#
# Usage: scripts/fetch-unicode-fixture.sh [unicode-version]

set -euo pipefail

version="${1:-17.0.0}"
url="https://www.unicode.org/Public/${version}/ucd/UnicodeData.txt"
root="$(cd "$(dirname "$0")/.." && pwd)"
out="${root}/src/document/__fixtures__/UnicodeData.math.txt"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

curl --fail --silent --show-error --location "$url" --output "$tmp"

if command -v sha256sum >/dev/null; then
  digest="$(sha256sum "$tmp" | cut -d' ' -f1)"
else
  digest="$(shasum -a 256 "$tmp" | cut -d' ' -f1)"
fi

{
  echo "# Source: ${url}"
  echo "# Source SHA-256: ${digest}"
  echo "# Excerpt: U+2100..U+214F and U+1D400..U+1D7FF, generated by scripts/fetch-unicode-fixture.sh"
  grep -E '^(21[0-4][0-9A-F]|1D[4-7][0-9A-F]{2});' "$tmp"
} >"$out"

echo "wrote $(grep -vc '^#' "$out") entries to ${out#"$root"/}"
